// Shared UserDefaults key constants
enum AppStorageKeys {
    static let swipeActionsEnabled = "swipeActionsEnabled"
    static let contributionGraphsEnabled = "contributionGraphsEnabled"
    static let activeAccountID = "activeAccountID"
    static let wrapRepositoryFileLines = "wrapRepositoryFileLines"
    static let lookupHistory = "lookupHistory"
    static let scopedSearchHistory = "scopedSearchHistory"
    static let hutchStatsBaseURL = "hutchStatsBaseURL"
    static let systemStatusSnapshotCache = "systemStatusSnapshotCache"
    static let systemStatusIncidentCache = "systemStatusIncidentCache"
    static let homeProjectsExpanded = "homeProjectsExpanded"
    static let pinnedHomeProjects = "pinnedHomeProjects"
    static let homeAssignedTicketsExpanded = "homeAssignedTicketsExpanded"
    static let homeBuildsExpanded = "homeBuildsExpanded"
    static let buildsAutoRefreshInterval = "buildsAutoRefreshInterval"
    static let buildsRepoFilter = "buildsRepoFilter"
    static let ticketFilterState = "ticketFilterState"
    static let ticketSavedFilters = "ticketSavedFilters"
    static let appTheme = "appTheme"
    static let displayDensity = "displayDensity"
}
